# Generated by Django 4.2.27 on 2026-05-27 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campuslocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campuslocation',
            options={'ordering': ['branch__name', 'name']},
        ),
        migrations.AlterField(
            model_name='campuslocation',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Leave blank to create a GLOBAL location that applies to ALL branches.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_locations', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='campuslocation',
            name='name',
            field=models.CharField(help_text="Human-readable label, e.g. 'Main Campus' or 'Lab 2'", max_length=150),
        ),
    ]
